export const GET_PROVINCES = 'GET_PROVINCES';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';
export const GET_PROVINCES_ERROR = 'GET_PROVINCES_ERROR';

export const GET_DISTRICTS = 'GET_DISTRICT';
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICT_SUCCESS';
export const GET_DISTRICTS_ERROR = 'GET_DISTRICT_ERROR';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR';

export const SEARCH_USER = 'SEARCH_USER';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_ERROR = 'SEARCH_USER_ERROR';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const SET_POST = 'SET_POST';
export const SET_URL_IMAGE = 'SET_URL_IMAGE';

export const SET_MENTIONS = 'SET_MENTIONS';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const GET_USERS_ONLINE = 'GET_USERS_ONLINE';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_IN = 'SIGN_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERRORS = 'LOGIN_ERRORS';

export const SHOW_LOADING_CLICK_BUTTON = 'SHOW_LOADING_CLICK_BUTTON';
export const HIDE_LOADING_CLICK_BUTTON = 'HIDE_LOADING_CLICK_BUTTON';
export const SHOW_LOADING_FETCH_DATA = 'SHOW_LOADING_FETCH_DATA';
export const HIDE_LOADING_FETCH_DATA = 'HIDE_LOADING_FETCH_DATA';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POST_OVER = 'FETCH_POST_OVER';

export const FETCH_POSTS_BY_ID = 'FETCH_POSTS_BY_ID';
export const FETCH_POSTS_BY_ID_SUCCESS = 'FETCH_POSTS_BY_ID_SUCCESS';
export const FETCH_POSTS_BY_ID_ERROR = 'FETCH_POSTS_BY_ID_ERROR';
export const FETCH_POSTS_BY_ID_OVER = 'FETCH_POSTS_BY_ID_OVER';

export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const RE_AUTH = 'RE_AUTH';
export const RE_AUTH_SUCCESS = 'RE_AUTH_SUCCESS';
export const RE_AUTH_FAIL = 'RE_AUTH_FAIL';

export const GET_CHATS = 'GET_CHATS';
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
export const GET_CHATS_ERROR = 'GET_CHATS_ERROR';
export const GET_CHAT_AFTER = 'GET_CHAT_AFTER';
export const GET_STATUS_CHATS = 'GET_STATUS_CHATS';
export const GET_STATUS_CHATS_SUCCESS = 'GET_STATUS_CHATS_SUCCESS';
export const GET_STATUS_CHATS_ERROR = 'GET_STATUS_CHATS_ERROR';
export const GET_STATUS_AFTER = 'GET_STATUS_AFTER';
export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_ERROR = 'GET_ROOMS_ERROR';
export const GET_ROOMS_AFTER = 'GET_ROOMS_AFTER';
export const CHANGE_VISIBLE_CREATE_ROOM = 'CHANGE_VISIBLE_CREATE_ROOM';
export const CHECK_JOIN_ROOM = 'CHECK_JOIN_ROOM';
export const CHECK_JOIN_ROOM_SUCCESS = 'CHECK_JOIN_ROOM_SUCCESS';
export const CHECK_JOIN_ROOM_ERROR = 'CHECK_JOIN_ROOM_ERROR';
export const GET_USER_CURRENT_ONL = 'GET_USER_CURRENT_ONL';
export const GET_MESSAGE_ROOM_AFTER = 'GET_MESSAGE_ROOM_AFTER';