//xs sm md lg xl theo thu tu tu nho den lon

export const GET_PROVINCES = 'GET_PROVINCES';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';
export const GET_PROVINCES_ERROR = 'GET_PROVINCES_ERROR';

export const GET_DISTRICTS = 'GET_DISTRICT';
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICT_SUCCESS';
export const GET_DISTRICTS_ERROR = 'GET_DISTRICT_ERROR';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';

export const SEARCH_USER = 'SEARCH_USER';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const SET_MENTIONS = 'SET_MENTIONS';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_IN = 'SIGN_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERRORS = 'LOGIN_ERRORS';

export const REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED';

export const SHOW_LOADING_CLICK_BUTTON = 'SHOW_LOADING_CLICK_BUTTON';
export const HIDE_LOADING_CLICK_BUTTON = 'HIDE_LOADING_CLICK_BUTTON';
export const SHOW_LOADING_FETCH_DATA = 'SHOW_LOADING_FETCH_DATA';
export const HIDE_LOADING_FETCH_DATA = 'HIDE_LOADING_FETCH_DATA';

export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_OVER = 'FETCH_POST_OVER';

export const FETCH_POSTS_BY_ID = 'FETCH_POSTS_BY_ID';
export const FETCH_POSTS_BY_ID_SUCCESS = 'FETCH_POSTS_BY_ID_SUCCESS';
export const FETCH_POSTS_BY_ID_OVER = 'FETCH_POSTS_BY_ID_OVER';