export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';
export const CLEAN_EVENTS = 'CLEAN_EVENTS';
export const SEND_EVENT_ADD_FRIEND = 'SEND_EVENT_ADD_FRIEND';
export const REMOVE_EVENT = 'REMOVE_EVENT';
export const REMOVE_EVENT_SUCCESS = 'REMOVE_EVENT_SUCCESS';
export const REMOVE_EVENT_ERROR = 'REMOVE_EVENT_ERROR';
export const REMOVE_ALL_EVENT = 'REMOVE_ALL_EVENT';
export const REMOVE_ALL_EVENT_SUCCESS = 'REMOVE_ALL_EVENT_SUCCESS';
export const REMOVE_ALL_EVENT_ERROR = 'REMOVE_ALL_EVENT_ERROR';
export const FETCH_HISTORYS = 'FETCH_HISTORYS';
export const FETCH_HISTORYS_SUCCESS = 'FETCH_HISTORYS_SUCCESS';
export const FETCH_HISTORYS_ERROR = 'FETCH_HISTORYS_ERROR';
export const FETCH_HISTORYS_OVER = 'FETCH_HISTORYS_OVER';
export const LOAD_MORE_HISTORYS = 'LOAD_MORE_HISTORYS';
export const CLEAN_HISTORYS = 'CLEAN_HISTORYS';

export const CLEAN_ERROR = 'CLEAN_ERROR';

export const GET_PROVINCES = 'GET_PROVINCES';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';
export const GET_PROVINCES_ERROR = 'GET_PROVINCES_ERROR';

export const GET_DISTRICTS = 'GET_DISTRICT';
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICT_SUCCESS';
export const GET_DISTRICTS_ERROR = 'GET_DISTRICT_ERROR';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR';

export const SEARCH_MENTIONS = 'SEARCH_MENTIONS';
export const SEARCH_MENTIONS_SUCCESS = 'SEARCH_MENTIONS_SUCCESS';
export const SEARCH_MENTIONS_ERROR = 'SEARCH_MENTIONS_ERROR';

export const SEARCH_USER = 'SEARCH_USER';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_ERROR = 'SEARCH_USER_ERROR';
export const SEARCH_USER_EMPTY = 'SEARCH_USER_EMPTY';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const SET_MENTIONS = 'SET_MENTIONS';

export const SEND_ADD_FRIEND_SUCCESS = 'SEND_ADD_FRIEND_SUCCESS';
export const FETCH_USER_BY_ID = 'FETCH_USER_BY_ID';
export const FETCH_USER_BY_ID_SUCCESS = 'FETCH_USER_BY_ID_SUCCESS';
export const FETCH_USER_BY_ID_ERROR = 'FETCH_USER_BY_ID_ERROR';
export const CLEAN_USER_BY_ID = 'CLEAN_USER_BY_ID';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const UPDATE_PHOTOURL_USER = 'UPDATE_PHOTOURL_USER';
export const UPDATE_PHOTOURL_USER_SUCCESS = 'UPDATE_PHOTOURL_USER_SUCCESS';
export const UPDATE_PHOTOURL_USER_ERROR = 'UPDATE_PHOTOURL_USER_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';
export const UPDATE_INTEREST = 'UPDATE_INTEREST';
export const UPDATE_INTEREST_SUCCESS = 'UPDATE_INTEREST_SUCCESS';
export const UPDATE_INTEREST_ERROR = 'UPDATE_INTEREST_ERROR';
export const REMOVE_INTEREST = 'REMOVE_INTEREST';
export const REMOVE_INTEREST_SUCCESS = 'REMOVE_INTEREST_SUCCESS';
export const REMOVE_INTEREST_ERROR = 'REMOVE_INTEREST_ERROR';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const SETTING_PHONE = 'SETTING_PHONE';
export const SETTING_PHONE_SUCCESS = 'SETTING_PHONE_SUCCESS';
export const SETTING_PHONE_ERROR = 'SETTING_PHONE_ERROR';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_IN = 'SIGN_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERRORS = 'LOGIN_ERRORS';

export const SHOW_LOADING_CLICK_BUTTON = 'SHOW_LOADING_CLICK_BUTTON';
export const HIDE_LOADING_CLICK_BUTTON = 'HIDE_LOADING_CLICK_BUTTON';
export const SHOW_LOADING_FETCH_DATA = 'SHOW_LOADING_FETCH_DATA';
export const HIDE_LOADING_FETCH_DATA = 'HIDE_LOADING_FETCH_DATA';
export const CHANGE_VISIBLE = 'CHANGE_VISIBLE';
export const HIDE_ANIMATE = 'HIDE_ANIMATE';
export const SHOW_ANIMATE = 'SHOW_ANIMATE';
export const SHOW_LOADING_DATA = 'SHOW_LOADING_DATA';
export const HIDE_LOADING_DATA = 'HIDE_LOADING_DATA';
export const SHOW_LOADING_FETCH_EVENTS = 'SHOW_LOADING_FETCH_EVENTS';
export const HIDE_LOADING_FETCH_EVENTS = 'HIDE_LOADING_FETCH_EVENTS';
export const CHANGE_BREAK = 'CHANGE_BREAK';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_POST_OVER = 'FETCH_POST_OVER';
export const LOAD_MORE_POST = 'LOAD_MORE_POST';
export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_ERROR = 'LIKE_POST_ERROR';
export const DISLIKE_POST = 'DISLIKE_POST';
export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS';
export const DISLIKE_POST_ERROR = 'DISLIKE_POST_ERROR';

export const FETCH_POSTS_BY_ID = 'FETCH_POSTS_BY_ID';
export const FETCH_POSTS_BY_ID_SUCCESS = 'FETCH_POSTS_BY_ID_SUCCESS';
export const FETCH_POSTS_BY_ID_ERROR = 'FETCH_POSTS_BY_ID_ERROR';
export const LOAD_MORE_POST_BY_ID = 'LOAD_MORE_POST_BY_ID';
export const FETCH_POSTS_BY_ID_OVER = 'FETCH_POSTS_BY_ID_OVER';
export const UNMOUNT_POST_BY_ID = 'UNMOUNT_POST_BY_ID';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';
export const FETCH_COMMENTS_BY_IDPOST = 'FETCH_COMMENTS_BY_IDPOST';
export const FETCH_COMMENTS_BY_IDPOST_SUCCESS = 'FETCH_COMMENTS_BY_IDPOST_SUCCESS';
export const FETCH_COMMENTS_BY_IDPOST_ERROR = 'FETCH_COMMENTS_BY_IDPOST_ERROR';

export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const RE_AUTH = 'RE_AUTH';
export const RE_AUTH_SUCCESS = 'RE_AUTH_SUCCESS';
export const RE_AUTH_FAIL = 'RE_AUTH_FAIL';

export const GET_CHATS = 'GET_CHATS';
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
export const GET_CHATS_ERROR = 'GET_CHATS_ERROR';
export const GET_CHAT_AFTER = 'GET_CHAT_AFTER';
export const GET_STATUS_CHATS = 'GET_STATUS_CHATS';
export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_ERROR = 'GET_ROOMS_ERROR';
export const GET_ROOMS_AFTER = 'GET_ROOMS_AFTER';
export const CHECK_JOIN_ROOM = 'CHECK_JOIN_ROOM';
export const CHECK_JOIN_ROOM_SUCCESS = 'CHECK_JOIN_ROOM_SUCCESS';
export const CHECK_JOIN_ROOM_ERROR = 'CHECK_JOIN_ROOM_ERROR';
export const GET_USER_CURRENT_ONL = 'GET_USER_CURRENT_ONL';
export const GET_MESSAGE_ROOM_AFTER = 'GET_MESSAGE_ROOM_AFTER';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const DELETE_ROOM = 'DELETE_ROOM';
export const FETCH_MESSAGES_IN_ROOM = 'FETCH_MESSAGES_IN_ROOM';
export const FETCH_MESSAGES_IN_ROOM_SUCCESS = 'FETCH_MESSAGES_IN_ROOM_SUCCESS';
export const FETCH_MESSAGES_IN_ROOM_ERROR = 'FETCH_MESSAGES_IN_ROOM_ERROR';